### ISSUE TITLE
Option to disable indentation

### ISSUE THREAD

**Issue by W4RH4WK** [marzer/tomlplusplus#120]
**Is your feature request related to a problem? Please describe.**
I'd like to have TOML output with sub-tables not getting indented. It's not really a problem, just a personal preference.

**Describe the solution you'd like**
A flag for the formatter: `allow_indentation`, defaults to true.
Or, if the flags property of the formatter defaults to no flags set, `disallow_indentation`.

**Additional context**
Instead of this:
```toml
[Display]
displayName = '\\.\DISPLAY1'
fpsLimit = 100
vsync = true
windowMode = 'Windowed'

    [Display.mode]
    height = 1080
    refreshRate = 60
    width = 1920

[Graphics]
anisotropicFiltering = 'Medium'
antiAliasing = 'Off'
```

I'd like to have this:
```toml
[Display]
displayName = '\\.\DISPLAY1'
fpsLimit = 100
vsync = true
windowMode = 'Windowed'

[Display.mode]
height = 1080
refreshRate = 60
width = 1920

[Graphics]
anisotropicFiltering = 'Medium'
antiAliasing = 'Off'
```
