### ISSUE TITLE
when build TOML from code,how to add comments from code?

### ISSUE THREAD

**Issue by yxw820603** [marzer/tomlplusplus#177]
hi, in my program, it ask user some simple question,get some data,then create toml data using code and serializing to a file.but that toml little bit complex, so i need add some comments in it.
i can not find any document (and example code) about how to add comment. 
for example,the code is:
```cpp
int num = /* ask user input */
toml::table root;
toml::table tbl;

tbl.emplace<int>("num",num);
tbl.emplace<string>("more_key","more_value");

root.emplace("Mytable",tbl);

// need some code here to add comment to whole table and "more_key"

cout<<root<<endl;
```
i expected output is:
```toml
#this is commend for whole table
[Mytable]
num = 1

# comment for more_key
more_key = "more_value"
```
