### ISSUE TITLE
Dotted keys can't define sub-tables within tables indirectly defined in header form

### ISSUE THREAD

**Issue by Validark** [marzer/tomlplusplus#61]
I believe based on the online library tester that this library fails to handle this valid TOML document:

```toml
[fruit.apple.texture]  # you can add sub-tables
smooth = true

[fruit]
apple.color = "red"
apple.taste.sweet = true
```

I haven't actually used this library outside of the browser, so all I got for you is a playground link: https://godbolt.org/z/T59E7d

Related: https://github.com/toml-lang/toml/issues/771

**Comment by marzer** [comment]
The behaviour is correct; that's not legal TOML. You can't mix `[table.headers]` and `dotted.keys`.

**Comment by Validark** [comment]
My mistake, I didn't scroll all the way down in https://github.com/toml-lang/toml/issues/771 to see that this issue is still being debated.

**Comment by marzer** [comment]
Aye, it's a pretty confusing part of the spec. Given the choice personally I'd remove `dotted.keys` from the language altogether.

**Comment by awvwgk** [comment]
I'm intrigued by this example, maybe I should rather ask this to the discussion in https://github.com/toml-lang/toml/issues/771, but it seems more related to this particular implementation to me.

Why would this TOML document be invalid

```toml
[fruit.apple.texture]  # you can add sub-tables
smooth = true

[fruit]
apple.color = "red"
apple.taste.sweet = true
```

but changing the order of the tables be valid instead if dotted keys were shorthands for inline tables? https://godbolt.org/z/ss9xsP

```toml
[fruit]
apple.color = "red"
apple.taste.sweet = true

[fruit.apple.texture]  # you can add sub-tables
smooth = true
```
